### ISSUE TITLE
Vull un cafè sapastre

### ISSUE THREAD

**Issue by dani-gallegos** [Josep-Pages/DIA2.P0-CursUdG#1]
Trobo a faltar els nostres cafès.

**Comment by Josep-Pages** [comment]
OSTI!!!! JO TAMBÉ!!!!!!  :-)

**Comment by dani-gallegos** [comment]
Ah!, i també col·laborar en aqeust repositori.

**Comment by dani-gallegos** [comment]
Petició acceptada

**Comment by Josep-Pages** [comment]
Vinga, a veure si en sóc capaç: 
### Recepta per poder fer un cafè amb els amics

**Comment by Josep-Pages** [comment]
a) anar-los a trobar al seu poble. Complicat si hi ha confinament municipal.
b) coincidir amb ells a la feina. Factible: cal canviar el dia d'anar-hi.
b.1) Cal preguntar a en Dani quin dia fa presència a la feina. Cal assegurar que no hi ha morus a la costa a la feina: elements pertorbadors a l'SI que en taquin el gaudi.

**Comment by gabyprogramem** [comment]
Provo si puc tancar aquesta issue
