### ISSUE TITLE
Petició col·laboració

### ISSUE THREAD

**Issue by MiquelBasart-UdG** [Josep-Pages/DIA2.P0-CursUdG#10]
Hola @Josep-Pages 
M'agrada molt la feina que estàs fent, m'agradaria ser col·laborador en aquest repositori

**Comment by MiquelBasart-UdG** [comment]
Podries fer-me una issue a https://github.com/MiquelBasart-UdG/Divendres.Miquel

**Comment by Josep-Pages** [comment]
FEta la "issue"

**Comment by Josep-Pages** [comment]
Feta la issue a ca'n Quel
